sudo: false

language: php

cache:
  directories:
    - $HOME/.composer/cache

services:
  - mysql

env:
  - DB_HOST: 127.0.0.1

matrix:
  fast_finish: true
  include:
    - php: 7.0
    - php: 7.1
    - php: 7.2
  
before_install:
  - phpenv config-add .travis-config.ini || return 0
  - if [[ $EXECUTE_COVERAGE != 'true' ]]; then phpenv config-rm xdebug.ini || return 0 ; fi
  - composer self-update

install:
  - travis_retry composer install --no-interaction --ignore-platform-reqs --prefer-source

script:
  - ./vendor/bin/phpunit
  - ./vendor/bin/phpcs --extensions=php --standard=PSR2 --ignore=test/Bootstrap.php --ignore=src/Entity/* src
