language: php

php: 
    - 5.5
    - 5.4
    - 5.3

matrix:
    allow_failures:
        - php: 5.5
env:
    - DB=sqlite

before-script:
    - composer install --dev --prefer-source

script: phpunit --configuration test/travis.xml
